Adjust for new agent to allow wait for startup

diff --git a/victoria-logs/knot-entrypoint b/victoria-logs/knot-entrypoint
--- a/victoria-logs/knot-entrypoint
+++ b/victoria-logs/knot-entrypoint
@@ -36,7 +36,9 @@ if [ "${KNOT_SERVER:-}" ]; then
   echo "Fetching agent binary for $ARCH"
 
   # Download the application from the server
-  if ! curl -sLk ${KNOT_SERVER}/agents/$url.zip | funzip > /usr/local/bin/knot; then
+  resolve_opt=""
+  if [ -n "${KNOT_SERVER_RESOLVE:-}" ]; then resolve_opt="--resolve ${KNOT_SERVER_RESOLVE}"; fi
+  if ! curl -sSLk $resolve_opt ${KNOT_SERVER}/agents/$url.zip | funzip > /usr/local/bin/knot; then
     echo >&2 "error: failed to fetch agent binary"
     exit 1
   fi
@@ -47,6 +49,8 @@ if [ "${KNOT_SERVER:-}" ]; then
 
   echo "Starting knot agent..."
   gosu ${KNOT_USER} /usr/local/bin/knot agent start 2>&1 &
+
+  gosu ${KNOT_USER} /usr/local/bin/knot agent wait-for-start >/dev/null 2>&1 || echo >&2 "Note: agent readiness cannot be verified."
 fi
 
 # If KNOT_SYSLOG_PORT is not defined or not 0 then route to agents syslogd port
